name: Felipe Dornelas
email: m@felipedornelas.com
author: Felipe Dornelas
url: https://felipedornelas.com

contact_page: contact
defaults:
  -
    scope:
      path: "contact"
    values:
      permalink: "/contact/"

source_url: https://github.com/felipead/felipead.github.io
github_url: https://github.com/felipead
twitter_url: https://twitter.com/felipead
linkedin_url: https://linkedin.com/in/felipead
resume_url: https://linkedin.com/in/felipead

exclude: ['Gemfile','Gemfile.lock','.git','.gitignore','README.md','LICENSE.txt']
