name: Felipe Dornelas
email: m@felipedornelas.com
author: Felipe Dornelas
url: http://felipedornelas.com

contact_page: aGVsbG8K
defaults:
  -
    scope:
      path: "contact"
    values:
      permalink: "/aGVsbG8K/"

source_url: http://github.com/felipead/felipead.github.io
github_url: http://github.com/felipead
twitter_url: http://twitter.com/felipead
soundcloud_url: http://soundcloud.com/felipead
mixcloud_url: http://mixcloud.com/felipead
instagram_url: http://instagram.com/felipedornelas
linkedin_url: http://linkedin.com/in/felipead
resume_url: https://www.dropbox.com/s/5f332ouwyff535v/felipe-dornelas_english_a4.pdf?dl=0

exclude: ['Gemfile','Gemfile.lock','.git','.gitignore','README.md','LICENSE.txt']
